<?php

namespace Database\Seeders;

use App\Models\categoria;
use Illuminate\Database\Seeder;

class CategoriaSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    $categorias = [
      'Polo',
      'Deportivo',
      'Clásico',
      'Casual',
      'Formal',
      'Fiesta',
      'Invierno',
      'Verano',
      'Accesorios',
      'Zapatos',
      'Ropa interior',
      'Ropa de baño',
      'Ropa de dormir',
      'Ropa para trabajo',
      'Ropa para ejercicio',
      'Ropa vintage',
      'Ropa de lujo',
      'Ropa ecológica',
      'Ropa de marca',
      'Ropa de segunda mano',
      'Ropa para eventos',
      'Ropa para ocasiones especiales',
      'Ropa para viajes',
      'Ropa casual urbana',
      'Ropa formal de negocios',
      'Ropa deportiva técnica',
      'Ropa de calle',
      'Ropa para fiestas nocturnas',
      'Ropa de diseñador',
      'Ropa artesanal',
      'Ropa para deportes acuáticos',
      'Ropa para montaña',
      'Ropa para camping',
      'Ropa para esquiar',
      'Ropa para senderismo',
      'Ropa para yoga',
      'Ropa para correr',
      'Ropa para ciclismo',
      'Ropa para natación',
      'Ropa para surf',
      'Ropa para buceo',
      'Ropa para deportes extremos',
      'Ropa para pesca',
      'Ropa para golf',
      'Ropa para tenis',
      'Ropa para béisbol',
      'Ropa para baloncesto',
      'Ropa para fútbol',
      'Ropa para rugby',
      'Ropa para voleibol',
      'Ropa para deportes de raqueta',
      'Ropa para deportes de equipo',
      'Ropa para deportes individuales',
      'Ropa para entrenamiento',
      'Ropa para competición',
      'Ropa para espectadores',
      'Ropa para aficionados',
      'Ropa para fanáticos',
      'Ropa para conciertos',
      'Ropa para festivales',
      'Ropa para teatro',
      'Ropa para ballet',
      'Ropa para ópera',
      'Ropa para danza',
      'Ropa para eventos culturales',
      'Ropa para eventos sociales',
      'Ropa para eventos corporativos',
      'Ropa para eventos académicos',
      'Ropa para eventos religiosos',
      'Ropa para ceremonias',
      'Ropa para rituales',
      'Ropa para celebraciones',
      'Ropa para festividades',
      'Ropa para ferias',
      'Ropa para exposiciones',
      'Ropa para conferencias',
      'Ropa para simposios',
      'Ropa para congresos',
      'Ropa para convenciones',
      'Ropa para reuniones',
      'Ropa para entrevistas',
      'Ropa para presentaciones',
      'Ropa para sesiones fotográficas',
      'Ropa para filmaciones',
      'Ropa para videos musicales',
      'Ropa para comerciales',
      'Ropa para películas',
      'Ropa para televisión',
      'Ropa para series',
      'Ropa para documentales',
      'Ropa para cortometrajes',
      'Ropa para largometrajes',
      'Ropa para animación',
      'Ropa para realidad virtual',
      'Ropa para realidad aumentada',
      'Ropa para videojuegos',
      'Ropa para eSports',
      'Ropa para competencias',
      'Ropa para torneos',
      'Ropa para partidas',
      'Ropa para prácticas',
      'Ropa para entrenamientos',
      'Ropa para scrimmages',
      'Ropa para playtests',
      'Ropa para game jams',
      'Ropa para hackathons',
      'Ropa para maratones',
      'Ropa para ultramaratones',
      'Ropa para triatlones',
      'Ropa para ironman',
      'Ropa para desfiles',
      'Ropa para pasarelas',
      'Ropa para exposiciones de moda',
      'Ropa para ferias de moda',
      'Ropa para semanas de la moda',
      'Ropa para eventos de moda',
      'Ropa para lanzamientos de moda',
      'Ropa para shows de moda',
      'Ropa para desfiles de moda',
      'Ropa para pasarelas de moda',
      'Ropa para exhibiciones de moda',
      'Ropa para presentaciones de moda',
      'Ropa para colecciones de moda',
      'Ropa para diseñadores de moda',
      'Ropa para modelos de moda',
      'Ropa para estilistas de moda',
      'Ropa para maquilladores de moda',
      'Ropa para peinadores de moda',
      'Ropa para productores de moda',
      'Ropa para directores de moda',
      'Ropa para revistas de moda',
      'Ropa para bloggers de moda',
      'Ropa para influencers de moda',
      'Ropa para celebridades de moda',
      'Ropa para VIPs de moda',
      'Ropa para críticos de moda',
      'Ropa para editores de moda',
      'Ropa para periodistas de moda',
      'Ropa para fotógrafos de moda',
      'Ropa para videógrafos de moda',
      'Ropa para estrellas de moda',
      'Ropa para estrellas emergentes de moda',
      'Ropa para gurús de moda',
      'Ropa para íconos de moda',
      'Ropa para pioneros de moda',
      'Ropa para innovadores de moda',
      'Ropa para disruptores de moda',
      'Ropa para trendsetters',
      'Ropa para influencers de estilo',
      'Ropa para fashionistas',
      'Ropa para estetas',
      'Ropa para creativos',
      'Ropa para visionarios',
      'Ropa para artistas',
      'Ropa para diseñadores',
      'Ropa para artesanos',
      'Ropa para artífices',
      'Ropa para constructores de tendencias',
      'Ropa para arquitectos de moda',
      'Ropa para escultores de estilo',
      'Ropa para pintores de vestuario',
      'Ropa para ilustradores de moda',
      'Ropa para escritores de moda',
      'Ropa para poetas de moda',
      'Ropa para compositores de moda',
      'Ropa para directores de estilo',
      'Ropa para curadores de moda',
      'Ropa para críticos de estilo',
      'Ropa para evaluadores de tendencias',
      'Ropa para pronosticadores de moda',
      'Ropa para observadores de moda',
      'Ropa para analistas de moda',
      'Ropa para estrategas de moda',
      'Ropa para planificadores de moda',
      'Ropa para asesores de moda',
      'Ropa para consultores de moda',
      'Ropa para mentores de moda',
      'Ropa para guías de moda',
      'Ropa para entrenadores de moda',
      'Ropa para maestros de moda',
      'Ropa para líderes de moda',
      'Ropa para gurús de estilo',
      'Ropa para apasionados de moda',
      'Ropa para entusiastas de moda',
      'Ropa para fanáticos de moda',
      'Ropa para devotos de moda',
      'Ropa para fanboys de moda',
      'Ropa para fangirls de moda',
      'Ropa para seguidores de moda',
      'Ropa para admiradores de moda',
      'Ropa para aficionados de moda',
      'Ropa para simpatizantes de moda',
      'Ropa para partidarios de moda',
      'Ropa para colaboradores de moda',
      'Ropa para contribuyentes de moda',
      'Ropa para aliados de moda',
      'Ropa para compañeros de moda',
      'Ropa para cómplices de moda',
      'Ropa para colaboradores de estilo',
      'Ropa para coleccionistas de moda',
      'Ropa para obsesivos de moda',
      'Ropa para maniáticos de moda',
      'Ropa para adictos de moda',
      'Ropa para enfermos de moda',
      'Ropa para pacientes de moda',
      'Ropa para terapeutas de moda',
      'Ropa para médicos de moda',
      'Ropa para curadores de estilo',
      'Ropa para sastres',
      'Ropa para modistas'
    ];

    foreach ($categorias as $nombre) {
      Categoria::create([
        'nombre' => $nombre,
      ]);
    }
  }
}